### ISSUE TITLE
Add example using complex ufl

### ISSUE THREAD

**Issue by jorgensd** [jorgensd/dolfinx-tutorial#10]

**Comment by ExtremOPS** [comment]
Hi @jorgensd,

I am trying to work on a complex example using dolfinx. It is in the field of acoustics; solving for the velocity and pressure with Taylor-Hood elements. I am happy to share any progress and code to be used for your tutorial.

Right now I have the problem that I want to integrate over domain in  a post processing step... However, I have no idea how this can be done with dolfinx. The integral I am trying to implement is (sorry for not knowing how - if possible at all - typeset LaTeX in Github.

\int_{\Omega} \frac{a}{2}\,Re[(v,v)] + \frac{b}{2}\,Re[(p,p)]

where `v` is the complex 2 dimensional velocity and `p` the complex scalar pressure amplitude. So far I have after solving (successfully) for `v` and `p`.

```python
pr, pi = ufl.real(p), ufl.imag(p)
vr, vi = ufl.real(v), ufl.imag(v)

F = a/2*(inner(pr,pr)+inner(pi,pi)) + b/2*(inner(vr,vr)+inner(vi,vi))
Eac = dolfin.fem.assemble_scalar(F*ufl.dx)
```
However, then I get an error message. I am pretty sure, that is not the way how it is supposed to be done but I cannot find the right one.

I've done in that way so far, because that is how I know it from dolfin...

**Comment by jorgensd** [comment]
Please add a minimal working code that can reproduce your error message. I’ll have a look at such a snippet

**Comment by ExtremOPS** [comment]
Thanks you very much. I really appreciate your tutorial you set up so far. 

The critical lines are after [L175 in MWE.txt](https://github.com/jorgensd/dolfinx-tutorial/files/6265872/MWE.txt)

**Comment by jorgensd** [comment]
As you are using the complex version of ufl, and the definition of `inner(a, b)` is `inner(a, conj(b))`, doesn't simply 
`inner(u, u)*dx` do what you want to do?

**Comment by ExtremOPS** [comment]
Thank you. I must have gotten something additional the first time wrong. 😕 

That fixes this now! I have to do some further validations and test and do not mind to share this code as complex example. 

I would probably then also write/ask again because in the next step I need to take the solution from the first stage as source term for the second stage. 

Just let me know if that is interesting for you.

**Comment by ExtremOPS** [comment]
Hi @jorgensd, thank you very much for the heads up! If you need me to do something (testing the tutorial etc.) let me know. Cheers

**Comment by jorgensd** [comment]
@ExtremOPS  A complex example has been added (and should be available on the web page in about 25 min).
