### ISSUE TITLE
Component-wise Dirichlet BCs

### ISSUE THREAD

**Issue by cmaurini** [jorgensd/dolfinx-tutorial#14]
I had bad time figuring out how to correctly write component-wise Dirichlet BCs. 
I was not able to find an example in the tutorial (maybe this is my fault). 
I think that adding something more explicit would be useful, like [here](https://gitlab.kitware.com/cmaurini/newfrac-core-numerics/-/blob/master/01-LinearElasticity.ipynb)

**Comment by jorgensd** [comment]
Good suggestion. I think it could be sensible to add a demonstration of this to the chapter: 
Subdomains and boundary conditions.
I would suggest a linear elasticity problem (as it is already covered in the demo: https://jorgensd.github.io/dolfinx-tutorial/chapter2/linearelasticity_code.html#), but instead of using traction using a prescribed deflection in $z$ direction.

Would you be fine with that?

**Comment by cmaurini** [comment]
yes, thanks!

**Comment by jorgensd** [comment]
Added in: https://jorgensd.github.io/dolfinx-tutorial/chapter3/component_bc.html

**Comment by cmaurini** [comment]
Dear Jorgen,

maybe, you want to replace ’top’ with 

```
def right(x):
    return np.isclose(x[0], L)
boundary_dofs_x = dolfinx.fem.locate_dofs_geometrical((V.sub(0), V0), right)

```

This will make a clearer example from the physical point of view, I think.

Also `Next we would like to constrain [...] to 0.0`, instead of `0.1`

**Comment by jorgensd** [comment]
> Dear Jorgen,
> 
> maybe, you want to replace ’top’ with
> 
> ```
> def right(x):
>     return np.isclose(x[0], L)
> boundary_dofs_x = dolfinx.fem.locate_dofs_geometrical((V.sub(0), V0), right)
> ```
> 
> This will make a clearer example from the physical point of view, I think.
> 
> Also `Next we would like to constrain [...] to 0.0`, instead of `0.1`

Ive fixed  this now.
